name: MFE CI Build

on:
  push:
    branches: [main, feature/**]
    paths:
      - 'app-shell/**'
      - 'shared-header/**'

  workflow_dispatch:  # ✅ Allow manual triggering from GitHub UI

jobs:
  build-app-shell:
    if: contains(github.event.head_commit.message, 'app-shell') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    env:
      REMOTE_SHARED_HEADER: ${{ secrets.REMOTE_SHARED_HEADER }}
    name: Build app-shell
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Verify environment variables
        run: |
          echo "REMOTE_SHARED_HEADER: $REMOTE_SHARED_HEADER"

      - name: Install dependencies
        run: npm ci
        working-directory: app-shell

      - name: Build app-shell
        run: npm run build
        working-directory: app-shell
      
      - name: Check if dist exists
        run: |
          echo "Listing contents of app-shell"
          ls -la app-shell
          echo "Listing contents of app-shell/dist"
          ls -la app-shell/dist

  build-shared-header:
    if: contains(github.event.head_commit.message, 'shared-header') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    env:
      REMOTE_SHARED_HEADER: ${{ secrets.REMOTE_SHARED_HEADER }}
    name: Build shared-header
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Verify environment variables
        run: |
          echo "REMOTE_SHARED_HEADER: $REMOTE_SHARED_HEADER"

      - name: Install dependencies
        run: npm ci
        working-directory: shared-header

      - name: Build shared-header
        run: npm run build
        working-directory: shared-header

      - name: Check if dist exists
        run: |
          echo "Listing contents of shared-header"
          ls -la shared-header
          echo "Listing contents of shared-header/dist"
          ls -la shared-header/dist